"""Version"""

__title__ = "dataclass_to_json"
__description__ = "Convert a dataclass structure to a JSON object."
__url__ = "https://github.com/DninoAdnane/dataclass_to_json"
__version__ = "1.1.0"
__author__ = "Adnane Guettaf"
__author_email__ = "adnane.guettaf@gmail.com"
__license__ = "MIT"
__copyright__ = "Copyright Adnane Guettaf"
